version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
        MONGO_INITDB_DATABASE: product-service-db
    volumes:
      - ./data:/data/db